version: '3.8'

services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: backend/Dockerfile.dev
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./backend/:/app/
      - /app/node_modules
    env_file:
      - .env

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile.dev
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    volumes:
      - ./frontend:/app
    env_file:
      - .env

