FROM node:18

# install dependencies
WORKDIR /app
COPY backend/package*.json ./
RUN --mount=type=cache,target=/backend/.npm \
    npm set cache /backend/.npm && \
    npm install

# get the source code
COPY backend /app/

CMD ["npm", "run", "dev"]
